### ISSUE TITLE
Packet flooding question

### ISSUE THREAD

**Issue by BlackCrawler** [wight-airmash/ab-server#103]
Some regular players reported about getting banned for packet flooding.
Related logs:
```
{"level":30,"time":1584832696829,"msg":"Player connected. {\"id\":17491,\"name\":\"User\",\"ip\":\"\",\"connection\":11376}","v":1}
{"level":30,"time":1584832724212,"msg":"Player connected. {\"id\":3470,\"name\":\"X\",\"ip\":\"\",\"connection\":11378}","
v":1}
{"level":30,"time":1584832726712,"msg":"Player connected. {\"id\":27144,\"name\":\"Y\",\"ip\":\"\",\"connection\":11380}","
v":1}
{"level":30,"time":1584832733296,"msg":"Player connected. {\"id\":33888,\"name\":\"Z\",\"ip\":\"\",\"connection\":11382}",
"v":1}
{"level":30,"time":1584832772692,"msg":"No Pong response. Kick player id17491.","v":1}
{"level":30,"time":1584832773065,"msg":"Player connected. {\"id\":17491,\"name\":\"User\",\"ip\":\"\",\"connection\":11384}","v":1}
{"level":30,"time":1584832775415,"msg":"No Ack request. Kick player id17491.","v":1}
{"level":30,"time":1584832783163,"msg":"Player connected. {\"id\":17491,\"name\":\"User\",\"ip\":\"\",\"connection\":11386}","v":1}
{"level":30,"time":1584832797148,"msg":"Packet flooding. {\"ip\":\"\",\"connection\":11386}","v":1}
{"level":30,"time":1584832797148,"msg":"Packet flooding ban. {\"ip\":\"\",\"connection\":11386}","v":1}
{"level":30,"time":1584832797148,"msg":"IP \"ERRORS_PACKET_FLOODING_DETECTED\"","v":1}
{"level":30,"time":1584832797198,"msg":"Packet flooding. {\"ip\":\"\",\"connection\":11387}","v":1}
```

Is it reasonable to increase `PACKETS_LIMIT_ANY` ?
Or to disable autoban `PACKETS_FLOODING_AUTOBAN`?
With `PACKETS_FLOODING_AUTOBAN == false` players will be kicked instead of banning?

**Comment by wight-airmash** [comment]
Yes, they will be only kicked with `PACKETS_FLOODING_AUTOBAN = false`.

> Is it reasonable to increase PACKETS_LIMIT_ANY

This can solve the problem for these players, but it also allows to create a potential more load on the server. And since this problem hasn't happened before, I'd like to find out the reasons. I noticed a lot of missed frames this week and don't know if this is due to the version 5.9.0 or if it is due to external factors, because there is something interesting in the log:

> {"level":30,"time":1584832772692,"msg":"No Pong response. Kick player id17491.","v":1}
> {"level":30,"time":1584832775415,"msg":"No Ack request. Kick player id17491.","v":1}

How many such records are in the logs this week?

**Comment by BlackCrawler** [comment]
Here is some stat:
<details>
  <summary>stat</summary>

|   date | total connected players | no_pong | no_ack |
|--------|-------------------------|---------|--------|
|  02-10 |                     339 |      26 |     32 |
|  02-11 |                     494 |      31 |     33 |
|  02-12 |                     484 |      43 |     69 |
|  02-13 |                     422 |      47 |     46 |
|  02-14 |                     410 |      41 |     41 |
|  02-15 |                     469 |      53 |     65 |
|  02-16 |                     413 |      29 |     33 |
|  02-17 |                     418 |      28 |     32 |
|  02-18 |                     481 |      47 |     50 |
|  02-19 |                     457 |      30 |     38 |
|  02-20 |                     477 |      51 |     56 |
|  02-21 |                     505 |      53 |     61 |
|  02-22 |                     427 |      43 |     41 |
|  02-23 |                     425 |      45 |     51 |
|  02-24 |                     478 |      38 |     50 |
|  02-25 |                     455 |      33 |     41 |
|  02-26 |                     545 |      61 |     82 |
|  02-27 |                     512 |      54 |     56 |
|  02-28 |                     539 |      41 |     45 |
|  02-29 |                     585 |      54 |     51 |
|  03-01 |                     643 |      41 |     48 |
|  03-02 |                     542 |      26 |     30 |
|  03-03 |                     493 |      42 |     41 |
|  03-04 |                     492 |      47 |     45 |
| **v3.8** |                         |         |        |
|  03-05 |                     517 |      41 |     55 |
|  03-06 |                     502 |      38 |     39 |
|  03-07 |                     496 |      56 |     54 |
|  03-08 |                     475 |      63 |     57 |
|  03-09 |                     497 |      49 |     48 |
|  03-10 |                     470 |      23 |     24 |
|  03-11 |                     530 |      36 |     47 |
|  03-12 |                     551 |      33 |     32 |
|  03-13 |                     634 |      61 |     64 |
|  03-14 |                     607 |      67 |     59 |
|  03-15 |                     550 |      53 |     63 |
|  03-16 |                     514 |      39 |     47 |
| **v3.9** |                         |         |        |
|  03-17 |                     669 |      64 |     81 |
|  03-18 |                     899 |     105 |    112 |
|  03-19 |                     876 |      82 |     87 |
|  03-20 |                     762 |      51 |     60 |
|  03-21 |                     713 |      64 |     67 |
|  03-22 |                     557 |      34 |     48 |

</details>

Don't see any regression after 3.9. It seems that ctf is getting more popular, so load on the server increases. 
I think, I will disable `PACKETS_FLOODING_AUTOBAN` for now.

**Comment by BlackCrawler** [comment]
Number of records `Packet flooding[ ban].`
<details>
  <summary>stat</summary>

|   date | length |
|--------|--------|
|  02-11 |      2 |
|  02-12 |      3 |
|  02-13 |      1 |
|  02-14 |      2 |
|  02-15 |      3 |
|  02-16 |      3 |
|  02-17 |      1 |
|  02-18 |      4 |
|  02-19 |      2 |
|  02-20 |      1 |
|  02-21 |      2 |
|  02-23 |      3 |
|  02-24 |      1 |
|  02-25 |      1 |
|  02-27 |      1 |
|  02-28 |      1 |
|  02-29 |     10 |
|  03-01 |      2 |
|  03-02 |      3 |
|  03-03 |      5 |
| **v3.8** |        |
|  03-06 |      2 |
|  03-07 |      1 |
|  03-09 |      3 |
|  03-10 |      1 |
|  03-11 |      1 |
|  03-13 |      1 |
|  03-14 |      1 |
|  03-16 |      1 |
| **v3.9** |        |
|  03-17 |      3 |
|  03-18 |      2 |
|  03-19 |      6 |
|  03-20 |      1 |
|  03-21 |      7 |
|  03-22 |      1 |

</details>

**Comment by wight-airmash** [comment]
Thank you for this stats! Look like it's time for re-profiling.

**Comment by BlackCrawler** [comment]
set `PACKETS_FLOODING_AUTOBAN` to false
