### ISSUE TITLE
Version 6 with worker threads support

### ISSUE THREAD

**Issue by wight-airmash** [wight-airmash/ab-server#106]
[v6-threads-develop branch](https://github.com/wight-airmash/ab-server/tree/v6-threads-develop).

As the game [becomes more popular](https://github.com/wight-airmash/ab-server/issues/103#issuecomment-602289609), this version can help to solve the performance problem.

In general, this is an update with performance issue fixes. This version has not been finished yet, but everything in 5.10.0 works here too, and some new features have been added. It also contains a lot of small changes, I will port them to the "single thread" version when finish this one, or, more likely, make a single version with the option to use worker threads.

What was changed:
- Removed custom resolver "module-alias". That is why almost all the files are changed.
- Updated project structure. Custom modes moved to `/src/modes`, `/src/server` is the base mode now.
- WS/HTTP endpoint in the worker. Slightly refactored admin code.
- User accounts serialization and saving in the worker. Now the data will be serialized and saved only if there were changes. Checking as before every 5 seconds.
- Refactored and optimized collisions detection.
- Deleted no longer required debug logs. Less work for the garbage collector: although debug logs may not have been displayed (due to log level), unnecessary objects were created anyway.
- Types for entities.
- Data serialization with [fast-json-stringify](https://github.com/fastify/fast-json-stringify).
- Chat (public, say and team) log in a separate file. May be useful for moderating or some alerts setup. `/logs/chat.log` by default, set `LOG_CHAT_FILE` empty string to disable.
- New network metrics. Current traffic, total transfered. Check with `/server` and `/server network`.
- `/server debug` was splitted into `/server debug`, `/server performance`, `/server network` and `/server frames`.
- `/lags` command to help players with understanding lags reasons. Gives the player information about when the server last detected lags on the player side and when it was last frame skip.
- Pino updated to [v6.0.0](https://github.com/pinojs/pino/releases/tag/v6.0.0).
- I gradually replace forEach with iterators for Set and Map. The code is less expressive, but it is much faster.
- The KEY packets are no longer be dropped after player lagging, only ACK packets. The solution was not the best one, the side effect (losing the airplane control for a short time) was worse than the problem being solved.
- Server side `/say` fix #51.

I'm not sure that the version doesn't contain any bugs, there were quite a lot minor changes, so don't forget to back up user accounts if you want to try it.

**Comment by wight-airmash** [comment]
Update:
- `THREADS=false` or `THREADS=true` to manually disable and enable workers.

**Comment by BlackCrawler** [comment]
Here is some stat for v6 version.
<details>
  <summary>stat</summary>
  
|                   date | total conns | total bots conns | max players | cnt of hours avg > 26 | total sf |
|------------------------|-------------|------------------|-------------|-----------------------|----------|
|                  02-10 |         339 |              459 |             |                       |      197 |
|                  02-11 |         494 |              728 |             |                       |      730 |
|                  02-12 |         484 |              661 |             |                       |      376 |
|                  02-13 |         422 |              730 |             |                       |      234 |
|                  02-14 |         410 |              798 |             |                       |     1134 |
|                  02-15 |         469 |              775 |             |                       |      341 |
|                  02-16 |         413 |              835 |             |                       |      343 |
|                  02-17 |         418 |              685 |             |                       |      544 |
|                  02-18 |         481 |              775 |             |                       |      339 |
|                  02-19 |         457 |              734 |             |                       |      289 |
|                  02-20 |         477 |              841 |             |                       |      349 |
|                  02-21 |         505 |              764 |             |                       |      648 |
|                  02-22 |         427 |              784 |             |                       |     2224 |
|                  02-23 |         425 |              758 |             |                       |     1510 |
|                  02-24 |         478 |              810 |             |                       |      898 |
|                  02-25 |         455 |              784 |             |                       |      595 |
|                  02-26 |         545 |              758 |             |                       |      362 |
|                  02-27 |         512 |              841 |             |                       |      330 |
|                  02-28 |         539 |              778 |             |                       |      501 |
|                  02-29 |         585 |              718 |             |                       |      421 |
|                  03-01 |         643 |              741 |             |                       |      424 |
|                  03-02 |         542 |              692 |             |                       |      197 |
|                  03-03 |         493 |              669 |             |                       |      116 |
|                  03-04 |         492 |              683 |             |                       |      230 |
|               **v5.8** |             |                  |             |                       |          |
|                  03-05 |         517 |              707 |             |                       |       80 |
|                  03-06 |         502 |              714 |             |                       |      227 |
|                  03-07 |         496 |              623 |             |                       |      450 |
|                  03-08 |         475 |              747 |             |                       |      311 |
|                  03-09 |         497 |              718 |             |                       |      335 |
|                  03-10 |         470 |              778 |             |                       |      367 |
|                  03-11 |         530 |              728 |             |                       |      324 |
|                  03-12 |         551 |              759 |             |                       |      180 |
|                  03-13 |         634 |              796 |             |                       |      348 |
|                  03-14 |         607 |              769 |             |                       |      372 |
|                  03-15 |         550 |              787 |             |                       |      534 |
|                  03-16 |         514 |              879 |             |                       |      909 |
|               **v5.9** |             |                  |             |                       |          |
|                  03-17 |         669 |              811 |             |                       |     1018 |
|                  03-18 |         899 |              817 |             |                       |      342 |
|                  03-19 |         876 |              850 |             |                       |      574 |
|                /03-20/ |         762 |              816 |             |                       |      838 |
|                /03-21/ |         713 |              774 |             |                       |     2029 |
|                /03-22/ |         603 |              818 |             |                       |     1607 |
|    **no-comp no-accs** |             |                  |             |                       |          |
|                  03-23 |         653 |              855 |             |                       |      838 |
|                  03-24 |         624 |              758 |             |                       |      180 |
|                  03-25 |         505 |              766 |             |                       |      279 |
|                  03-26 |         547 |              790 |             |                       |      338 |
|                /03-27/ |         511 |              750 |             |                       |      948 |
|                /03-28/ |         563 |              725 |             |                       |     1539 |
|              **v5.10** |             |                  |             |                       |          |
|                /03-29/ |         565 |              772 |          34 |                     3 |      639 |
|                  03-30 |         552 |              832 |          35 |                     1 |      653 |
|                  03-31 |         702 |              802 |          44 |                     3 |      613 |
|                  04-01 |         804 |              791 |          41 |                     6 |      688 |
|                  04-02 |         742 |              757 |          33 |                     1 |      531 |
|                /04-03/ |         819 |              790 |          43 |                     5 |     1420 |
|                /04-04/ |         717 |              756 |          42 |                     5 |     1557 |
|                /04-05/ |         739 |              818 |          44 |                     5 |     2461 |
|                  04-06 |         662 |              769 |          37 |                     2 |      527 |
|                  04-07 |         750 |              745 |          35 |                     2 |      647 |
|                  04-08 |         883 |              693 |          44 |                     6 |     1786 |
|                  04-09 |         738 |              805 |          40 |                     3 |      471 |
|  **v6 multi-threaded** |             |                  |             |                       |          |
|                /04-10/ |         771 |              723 |          38 |                     6 |      616 |
|                /04-11/ |         745 |              838 |          39 |                     4 |      911 |
| **v6 single-threaded** |             |                  |             |                       |          |
|                /04-12/ |         675 |              771 |          43 |                     7 |     1355 |

</details>

It seems that multi-threaded version is better (in terms of total skipped frames) even on the server with one cpu.

Also the load on weekends (dates enclosed in / /)  is always higher than other days. Compare 04-01  and 04-04 or 04-05. Maybe the host of the DO droplet is overloaded on weekends, dunno.

**Comment by wight-airmash** [comment]
> Maybe the host of the DO droplet is overloaded on weekends, dunno.

It could be. For comparison yesterday there were several intense games with online about 40 players. One during the day, the other at night. During the day there was no lag/jerks feeling, the frame skip rate was within the limits when it was not felt, while at night skip rate was extremely unpleasant, probably a lot of several frames in a row with jerks as a visual result. I can't say that the games were different, in both cases they were defensive (a lot of out packets, mostly player_update) with an intensive escorting and recaping, both with copters (a bit more projectiles), with 1-2 goliaths. Maybe I should add more per match metrics.

Also try to log CPU steal time to check the dependence of frame skips on it.

**Comment by BlackCrawler** [comment]
Here are the logs from yesterday. I roughly mark the boundaries of intense games based on max players and cpu usage. Time is UTC.
<details>
  <summary>players</summary>

| date           | max | avg |
|----------------|-----|-----|
| 04-12_10-44    |  15 |  14 |
| 04-12_11-44    |  18 |  15 |
| 04-12_12-44    |  20 |  17 |
| 04-12_13-44    |  15 |  14 |
| 04-12_14-44    |  24 |  14 |
| **game-1**     |     |     |
| 04-12_15-44    |  42 |  32 |
| 04-12_16-44    |  42 |  37 |
| **game-1 end** |     |     |
| 04-12_17-44    |  30 |  25 |
| **game-2**     |     |     |
| 04-12_18-44    |  42 |  29 |
| 04-12_19-44    |  38 |  30 |
| **game-2 end** |     |     |
| 04-12_20-44    |  26 |  23 |
| **game-3**     |     |     |
| 04-12_21-44    |  41 |  32 |
| 04-12_22-44    |  43 |  36 |
| 04-12_23-44    |  36 |  31 |  

</details>

<details>
  <summary>cpu</summary>
  
```
-------------------------- analysis date: 2020/04/12 --------------------------
00:00:02  cpu  %usr %nice %sys %irq %softirq  %steal %guest  %wait %idle  _cpu_
15:00:02  all    19     0    6    0        2       0      0      0    73
15:10:02  all    23     0    8    0        4       0      0      0    65
********GAME-1*********
15:20:02  all    32     0    7    0        3       0      0      0    57
15:30:02  all    28     0    8    0        4       0      0      0    59
15:40:02  all    32     0    8    0        5       0      0      0    55
15:50:02  all    35     0    9    0        5       0      0      0    51
16:00:02  all    33     0   10    0        6       0      0      0    50
16:10:02  all    35     0    9    0        5       0      0      0    51
16:20:02  all    28     0    8    0        4       0      0      0    59
********GAME-1 END*********
16:30:02  all    20     0    6    0        3       0      0      0    71
16:40:02  all    22     0    6    0        2       0      0      0    70
16:50:02  all    24     0    5    0        2       0      0      0    69
17:00:02  all    22     0    5    0        2       0      0      0    71
17:10:02  all    27     0    5    0        2       0      0      0    65
17:20:02  all    22     0    6    0        3       0      0      0    69
17:30:02  all    23     0    6    0        3       0      0      0    67
17:40:02  all    31     0    7    0        3       1      0      0    58
17:50:02  all    23     0    6    0        3       0      0      0    68
18:00:02  all    26     0    6    0        2       0      0      0    65
********GAME-2*********
18:10:02  all    36     0    6    0        3       0      0      0    55
18:20:02  all    23     0    6    0        3       0      0      0    68
18:30:02  all    33     0    7    0        4       0      0      0    55
18:40:02  all    45     0    9    0        5       0      0      0    40
18:50:02  all    24     0   10    0        5       0      0      0    61
19:00:02  all    25     0    7    0        4       0      0      0    64
19:10:02  all    31     0    8    0        4       0      0      0    57
19:20:02  all    39     0    7    0        3       0      0      0    50
19:30:02  all    44     0    6    0        3       0      0      0    46
********GAME-2 END*********
19:40:02  all    23     0    5    0        2       0      0      0    69
19:50:02  all    20     0    5    0        2       0      0      0    73
20:00:02  all    14     0    5    0        2       0      0      0    78
20:10:02  all    19     0    6    0        2       0      0      0    72
20:20:02  all    18     0    5    0        2       0      0      0    74
20:30:02  all    24     0    6    0        2       0      0      0    68
20:40:02  all    28     0    6    0        3       0      0      0    63
20:50:02  all    17     0    6    0        2       0      0      0    75
21:00:02  all    24     0    7    0        3       0      0      0    65
21:10:02  all    16     0    6    0        2       0      0      0    75
21:20:02  all    23     0    7    0        3       0      0      0    66
21:30:02  all    23     0    8    0        4       0      0      0    65
********GAME-3*********
21:40:02  all    34     0    9    0        5       0      0      0    53
21:50:02  all    41     0    8    0        5       0      0      0    46
22:00:02  all    35     0    9    0        5       0      0      0    51
22:10:02  all    29     0    9    0        5       0      0      0    58
22:20:02  all    30     0   10    0        5       0      0      0    56
22:30:02  all    33     0    9    0        5       0      0      0    53
22:40:02  all    29     0    8    0        4       0      0      0    58
22:50:02  all    32     0    7    0        4       0      0      0    58
23:00:02  all    26     0    8    0        3       0      0      0    63
23:10:02  all    34     0    7    0        4       0      0      0    56
23:20:02  all    24     0    7    0        3       0      0      0    65
23:30:02  all    29     0    6    0        3       0      0      0    61
23:40:02  all    35     0    6    0        3       0      0      0    56
23:50:02  all    25     0    7    0        3       0      0      0    65

```
</details>

<details>
  <summary>processes</summary>

```
-------------------------- analysis date: 2020/04/12 --------------------------
00:00:02    pid command  cpu% |   pid command  cpu% |   pid command  cpu%_top3_
15:00:02   5108 node      12% | 10316 tokio-ru   6% | 10885 airmash-   4%
15:10:02   5108 node      15% | 10885 airmash-  10% | 10696 nginx      4%
********GAME-1*********
15:20:02   5108 node      16% | 10885 airmash-  15% | 10696 nginx      5%
15:30:02   5108 node      17% | 10885 airmash-  12% | 10696 nginx      6%
15:40:02   5108 node      21% | 10885 airmash-  18% | 10696 nginx      6%
15:50:02  10885 airmash-  28% |  5108 node      21% | 10696 nginx      7%
16:00:02   5108 node      22% | 10885 tokio-ru  10% | 10696 nginx      8%
16:10:02   5108 node      21% | 11622 airmash-  14% | 10696 nginx      7%
16:20:02  11622 tokio-ru  19% |  5108 node      17% | 10696 nginx      6%
********GAME-1 END*********
16:30:02   5108 node      16% | 12030 airmash-  13% | 10696 nginx      5%
16:40:02  12030 airmash-  18% |  5108 node      15% | 10696 nginx      4%
16:50:02   5108 node      12% | 12030 airmash-  11% | 10696 nginx      4%
17:00:02   5108 node      12% | 12030 airmash-  11% | 10696 nginx      3%
17:10:02  12030 airmash-  17% |  5108 node      13% | 10696 nginx      4%
17:20:02   5108 node      14% | 12030 airmash-  13% | 10696 nginx      5%
17:30:02   5108 node      16% | 12030 airmash-  15% | 10696 nginx      5%
17:40:02  12030 airmash-  23% |  5108 node      18% | 10696 nginx      6%
17:50:02  12030 airmash-  15% |  5108 node      14% | 10696 nginx      5%
18:00:02  12030 airmash-  13% |  5108 node      13% | 10696 nginx      4%
********GAME-2*********
18:10:02  12030 airmash-  19% |  5108 node      15% | 10696 nginx      5%
18:20:02   5108 node      16% | 12030 airmash-  12% | 10696 nginx      6%
18:30:02  12030 airmash-  20% |  5108 node      18% | 10696 nginx      7%
18:40:02   5108 node      21% | 12030 tokio-ru  21% | 10696 nginx      8%
18:50:02   5108 node      20% | 10696 nginx     10% | 13825 tokio-ru   4%
19:00:02   5108 node      17% | 13959 airmash-  12% | 10696 nginx      7%
19:10:02  13959 airmash-  19% |  5108 node      17% | 10696 nginx      6%
19:20:02  13959 airmash-  26% |  5108 node      17% | 10696 nginx      6%
19:30:02  13959 airmash-  29% |  5108 node      15% | 10696 nginx      5%
********GAME-2 END*********
19:40:02  13959 airmash-  16% |  5108 node      12% | 10696 nginx      4%
19:50:02  13959 airmash-  12% |  5108 node      12% | 10696 nginx      4%
20:00:02   5108 node      12% | 13959 airmash-   9% | 10696 nginx      4%
20:10:02  13959 airmash-  17% |  5108 node      15% | 10696 nginx      5%
20:20:02  13959 airmash-  14% |  5108 node      13% | 10696 nginx      5%
20:30:02  13959 airmash-  17% |  5108 node      13% | 10696 nginx      4%
20:40:02  13959 airmash-  20% |  5108 node      14% | 10696 nginx      5%
20:50:02   5108 node      14% | 13959 airmash-  11% | 10696 nginx      5%
21:00:02  13959 airmash-  18% |  5108 node      16% | 10696 nginx      6%
21:10:02   5108 node      13% | 13959 airmash-   8% | 10696 nginx      5%
21:20:02   5108 node      17% | 13959 airmash-  13% | 10696 nginx      7%
21:30:02   5108 node      19% | 13959 airmash-  11% | 10696 nginx      8%
********GAME-3*********
21:40:02   5108 node      22% | 13959 airmash-  21% | 10696 nginx      8%
21:50:02  13959 airmash-  30% |  5108 node      20% | 10696 nginx      8%
22:00:02   5108 node      20% | 10696 nginx      9% | 18343 airmash-   4%
22:10:02   5108 node      20% | 18343 airmash-  14% | 10696 nginx      8%
22:20:02   5108 node      20% | 10696 nginx      9% | 18343 tokio-ru   8%
22:30:02   5108 node      20% | 18996 airmash-  14% | 10696 nginx      8%
22:40:02   5108 node      19% | 18996 airmash-  12% | 10696 nginx      8%
22:50:02  18996 airmash-  17% |  5108 node      17% | 10696 nginx      6%
23:00:02   5108 node      16% | 18996 tokio-ru  12% | 19896 airmash-   7%
23:10:02  19896 airmash-  17% |  5108 node      16% | 10696 nginx      6%
23:20:02   5108 node      16% | 19896 tokio-ru  13% | 10696 nginx      7%
23:30:02   5108 node      16% | 20448 airmash-  13% | 10696 nginx      6%
23:40:02  20448 airmash-  19% |  5108 node      15% | 10696 nginx      6%
23:50:02  20448 tokio-ru  17% |  5108 node      15% | 10696 nginx      6%
```
  
</details>

I don't see any anomalies in the night game. And it seems that the host is ok, since stealing% is 0.
I don't understand why the `airmash-ctf` process (bots) is replaced with `tokio-rust` process sometimes. Maybe bug in atop.
