### ISSUE TITLE
Version 6 thread issue: "uv loop at [address] has open handles"

### ISSUE THREAD

**Issue by vjk3** [wight-airmash/ab-server#108]
I was excited to download and try out v6 but got stuck here when running the server. Is there anything special that I need to do that is different from the process of launching a v5 server?

I'm on Mac OS Catalina (10.15.4) running latest node (v13.12.0) inside fish shell.

Debug dump for reference:
```
node dist/app.js
Enter PEM pass phrase:
uv loop at [0x700013a6eb08] has open handles:
[0x10465da00] prepare (active)
	Close callback: 0x412f737463656a6f 
	Data: 0x10465d290 
	(First field): 0x104660fd0 
[0x10465d3f0] check (active)
	Close callback: 0x547465730000000a 
	Data: 0x10465d290 
	(First field): 0x104660fd0 
[0x1046610a0] timer (active)
	Close callback: 0x16418c6661510c02 
	Data: 0x104660fd0 
[0x10465a040] async (active)
	Close callback: 0x0 
	Data: 0x104659f70 
[0x10477a2f0] poll (active)
	Close callback: 0x10515c788 
	Data: 0x0 
uv loop at [0x700013a6eb08] has 5 open handles in total
node[822]: ../src/debug_utils.cc:322:void node::CheckedUvLoopClose(uv_loop_t *): Assertion `0 && "uv_loop_close() while having open handles"' failed.
 1: 0x1011c23b5 node::Abort() (.cold.1) [/usr/local/bin/node]
 2: 0x10009c059 node::Abort() [/usr/local/bin/node]
 3: 0x10009bec1 node::Assert(node::AssertionInfo const&) [/usr/local/bin/node]
 4: 0x10002c5ee node::CheckedUvLoopClose(uv_loop_s*) [/usr/local/bin/node]
 5: 0x100132cd4 node::worker::WorkerThreadData::~WorkerThreadData() [/usr/local/bin/node]
 6: 0x10012f658 node::worker::Worker::Run() [/usr/local/bin/node]
 7: 0x100132f99 node::worker::Worker::StartThread(v8::FunctionCallbackInfo<v8::Value> const&)::$_2::__invoke(void*) [/usr/local/bin/node]
 8: 0x7fff6dd36109 _pthread_start [/usr/lib/system/libsystem_pthread.dylib]
 9: 0x7fff6dd31b8b thread_start [/usr/lib/system/libsystem_pthread.dylib]
fish: 'node dist/app.js' terminated by signal SIGABRT (Abort)
```

**Comment by wight-airmash** [comment]
> node dist/app.js
> Enter PEM pass phrase:

It may be necessary to provide the [passphrase](https://unetworking.github.io/uWebSockets.js/generated/interfaces/appoptions.html#passphrase) option.

**Comment by vjk3** [comment]
oh, the passphrase has been entered, the shell is not showing it because it's sensitive info 😀
Without the passphrase it won't proceed further.

After opening this issue, I went back and tried running it again after restarting the PC, just to make sure there are no open node files or components running in the background (which is what it seems to be complaining about). Unfortunately I have not had any success and the issue still remains.

As I'm out of other ideas and Google search didn't turn up anything helpful, I'll ask the question on StackOverflow and update this thread if I get any useful response from the community.

Please feel free to close this issue if you don't wish to proceed further, anyone else having the same problem can reopen it if they want. Thank you for your time, I'm super excited about perf improvements and can't wait to get this running. Cheers 👍

**Comment by wight-airmash** [comment]
Should be fixed in https://github.com/wight-airmash/ab-server/commit/6bfd85ea2407e548529667142680f280a2ed881f

I was a bit confused that there were no other logs, but actually there are:
```logs
ERROR: Error starting accounts worker.
FATAL: Accounts worker is down: {"exitCode":1}
```

---
However "uv loop" exception can be still here when the server stops. This relates with uWebSockets.js using threads and doesn't affect the game server working.

**Comment by vjk3** [comment]
The fix worked!

I'm seeing slightly higher core utilization with workers and a consequent average temperature drop of about 5 to 10 °C (from a toasty 98 °C to bearable 86 °C) with workers.

Btw,  I was running spatie's bots (n=10) in CTF mode when collecting the stats.

![node workers are great](https://user-images.githubusercontent.com/43559556/79071939-fa86df80-7cfb-11ea-807b-56be64dc4e8c.png)

I'm on an old dual-core i5 MacBook Air 2014. Will be interested to see how others are doing with beefier procs. Great work @wight-airmash, thanks and cheers again 👏

**Comment by wight-airmash** [comment]
As a fast check during the development, I did the tests with "number-bots" (the author unfortunately removed the repository). They emit a lot of KEY flood-packets, what is bad for production, but not for the test: more than 20000 for 50 bots, when the normal human-like value is about 4000-5000 for such online.

I had 0 frame skips during 20 minutes with active 5000 accounts file and forcefully turned on its periodic autosave. Under the same conditions on the same hardware it is simply impossible to play using single thread version (5.10), game loop constantly exceeds 16ms, a lot of frame skips, netcode uses a lot of game loop time to broadcast all the packets.

But, of course, for this version it needs appropriate hardware. Running it on a single core without multithreading support will not increase performance.

![bots test](https://user-images.githubusercontent.com/38955076/79074540-b0026480-7cf5-11ea-9173-86409f1acd55.png)

**Comment by vjk3** [comment]
Perhaps you can advise me on how I can tune the performance on my machine (if it's possible, my PC is quite old). Right now I'm maxing out at 15 bots without melting my system down.

If you have more info on this subject, please let me know where we can discuss in detail, thanks 😀

**Comment by wight-airmash** [comment]
Try limit CPU usage for the bots container(s), there are options like `--cpu-period`, `--cpu-quota` or `--cpuset-cpus`, [docker run reference](https://docs.docker.com/engine/reference/run/#cpu-period-constraint).

**Comment by vjk3** [comment]
Thank you for that tip! I'm running them directly on node.js without docker but apparently there's a way to mimic this and [throttle CPU on specific processes directly](https://bencane.com/2013/09/09/setting-process-cpu-priority-with-nice-and-renice/) with `nice` and `renice`. Will see if that can be used to get more bots into my CTFs 😀
