### ISSUE TITLE
Revert broken changes to dev CTF

### ISSUE THREAD

**Issue by occasionallydavid** [wight-airmash/ab-server#110]
Hi wight,

In reference to the proliferation of zooming, I once wrote on Reddit, "none of us is smart enough to design Airmash, only dumb enough to be addicted". I find myself recalling that on noticing at least one of the "non-predator monoculture" planes, the Tornado, is rendered useless for escort or offense in CTF by changes you have recently introduced.

I'd like to request you revert balance changes that have fundamentally impacted the viability of Tornado in CTF, and please spend at least a few weeks playing Tornado, or in fact any plane except predator, before attempting any further changes.

The changes are obviously incomplete, as fixed infernos and shields continue to spawn with the same fixed probability as before, even though upgrade probability has significantly decreased, one of the only methods of coping with a fast plane having a shield while flying an otherwise slow plane.

During my most recent game, after making 18 kills, only 3 of which were bots, and with 2 flags already captured, I had only secured a single box. In order to escort, the Tornado requires at a minimum 3 speed ups, which is only sufficient to match the flag. 5 are required to catch up. Given your new changes and this sample session, a Tornado must make 54 kills during **a hypothetical game that must continue to run for 6 caps** just in order to contribute as has always been possible since Airmash was first released.

**Comment by occasionallydavid** [comment]
I'd further add regarding the obvious defectiveness of this change, if reward for attacking a bot is being reduced, so should the bot's aggressiveness (lower damage) as well as the points transfer (perhaps even something like 10% normal), otherwise slow planes are tied up making endless pointless kills they cannot ignore without ending up dead

**Comment by wight-airmash** [comment]
Thanks for the feedback.

Perhaps most importantly thing, that some players are missing, this (upgrades) is an experimental change. Like the previous experimental changes ([1](https://github.com/wight-airmash/ab-server/tree/experiment/cap-if-returned), [2](https://github.com/wight-airmash/ab-server/tree/experiment/invisible-prowlers)), it is not included in the main branch. Moreover, most of the changes made earlier during this server development were optional and can be disabled in the server settings.

Next, what problem I'm trying to solve. The current implementation of bots and the server (v5) creates an imbalance in strategies: 
1. The bots are too easy to farm upgrade. Within 3-5 minutes, 5-10 upgrades accumulate without problems, which greatly devalues upgrades itselves. It is hardly possible to do this by playing against humans, even if they are not the strongest players. A person who has been killed several times will play more carefully, or avoid the battle with you at all. It will complicate and slow down the farm, even for an experienced player. Bots can die endlessly, they won't get bored of it, so it is possible to kill them and farm upgrades with no limits (without any balance).
2. The strategy of the game in defense (turtling) allows you to take advantage of p.1 and stretch the game without time constraints. When dying, the player quickly respawn near the base and continues to farm. I have watched the games when teams only sat on defense for 30 minutes and more, even without trying to capture the opponent's flag (we are still talking about capturing the flag mode), until the opponents get bored and start to leave the game, or until some strong player joins, brings an imbalance of forces and does all the work. What is this if not an example of imbalance in the mechanics of the game.

What changes are tested and how are they supposed to work and affect the game?
1. The chance of an upgrade drop from the bots has been halved. It is assumed that the time spent on the farming will become incommensurable with the obtained effect. I will note that for the humans the chance of drop has not changed.
2. Added linear gradient of chance of an upgrades drop (from the base to the center of the map). The closer a player is to his base, the less chance it has of getting an upgrade. Inside the base, the drop is completely disabled. It is assumed that if a team decides to stay in the base limitlessly, it will start losing resources (upgrades) for a while. This is an attempt to balance the turtle strategy.

As with any changes related to the balance of the game, it requires testing and adjustment of parameters. It is not surprising that the current implementation has issues and may not work as intended at all. This is what the development server is for.

**Comment by airmash-m4** [comment]
Hi all, m4 here. Firstly, nice work wight, I really appreciate all you've done to keep the game alive.

I have noticed a distinct lack of ups as compared to previously. I know turtling is an issue and there are some players who abuse bot farming (H springs to mind) for the ups, but as it stands I think it has gone back too far in the other direction.

Normally I prefer to play as a capper or escorter, but will often play D for couple minutes to pick up 3-4 ups that I can apply once I lift to give me the best chance. In the recent games, I've only managed to accumulate 1 or 2 ups the entire game.

Idea:
Increase the gradient to the enemies base so ups are as likely as previously (or maybe more?)  when killing the enemy near their base. This would encourage players to be more aggressive. The problem is the base are natural mixing points. With the current probability of an up being highest in mid map, the number of kills there is so slow that we end up accumulating less ups overall. Ironically you probably need a few speed upgrades to even play mid-D detect style.

Again, thanks for the work you're putting in. These are just my 2c :)

**Comment by BlackCrawler** [comment]
I really like that wight tries to balance this stuff. Good work!
As a predator offensive player it is really frustrating to lose your upgrades, while defenders keep theirs.

As an alternative solution, I can think of not resetting your upgrades on death and limiting the maximum number of upgrades your can apply to e.g. 8. 
I didn't think thoroughly about these changes, so can't say what implications would be.

**Comment by BlackCrawler** [comment]
Also I agree with derps (as an occasional heli player) that the current changes is heavily influenced by an offensive predators culture. It was hard to play as heli before these changes (im not pro heli) and I will not even try to play heli after these changes. Since I can't farm upgrades on def, I am supposed to fly over the map to try to kill some pro predators (!) and try to collect 4-5 boxes (that will be stolen).

**Comment by wight-airmash** [comment]
@airmash-m4 and @BlackCrawler, thanks for the ideas.

About helis: after completion (or rejection) of this update I'm going to update damage balance, especially for helis and return the guaranteed survival for enough def upgraded copters after 2 predator missiles (of course, it will affect other types of aircraft as well).

---
Updated. Now the chance is calculated separately for bots and humans.

**Bots**
Chance for bots killed inside the flag base (no matter what own or enemy) is 0.
The base chance value is 25%. Within 8000 (map is 32 768×16 384) the closer to your base you kill a bot, the lower your chance (but not less than 3%).

**Humans**
Distance from the own base no longer affects the chance.

Chance for humans killed inside the flag base (no matter what own or enemy) is 3% (this mechanics isn't finished yet as I wanted and still too oversimplified, will be updated soon). The base chance value is 60%. Chance varies from 35% to 85%. There are 4 factors that affect the chance.
1. K/d ratio of killer and victim (bots don't count). Affects within ≈8% of both plus and minus.
2. PvP kill streak within the game. If the killer killed the victim several times in a row, the chance is reduced. If the victim kills the killer with a kill streak, the chance goes up. Affects within ≈8% of both plus and minus.
3. Upgraded state ratio of killer and victim. So far, just compare the number of applied upgrades regardless of their type. If you kill the player with more applied upgrades, the chance goes up, and vice versa. Affects within ≈8% of both plus and minus.

These three factors make it possible to get 85%, or 35%.

4. Common reduce [factor](https://www.wolframalpha.com/input/?i=1%2F%28%28x+%2B+4%29%5E%281%2F%283+-+x%2F100%29%29+-+1%29%2C+x+%3E+4%2C+x+%3C+100), depends on available and applied player upgrades, applies only when player has >= 5 upgrades. Something similar to @BlackCrawler suggestion, but without strict restrictions on collected upgrades. Complicates the limitless collection of upgrades. It is applies on to the resulting value after 3 first factors have been applied. The final value cannot be less than 35%.

Example for the upgrades reduce factor. If I have 3002 applied upgrades and 1 free (6 total), my reduce factor is 0.84, so if I have 50% chance after 3 pvp factors, the result value is 42%.

---
Again, everything is in testing and adaptation process.

**Comment by wight-airmash** [comment]
Experiments are stopped until v6 code publication.
