### ISSUE TITLE
sometimes score is empty when killing a player that is too close

### ISSUE THREAD

**Issue by dmiddlecamp** [wight-airmash/ab-server#12]
While playing as tornado, about 25-50% of the time if I'm too close (within a few ships  distance), the server doesn't seem to return a score (not displayed on screen, player rank doesn't change).

**Comment by wight-airmash** [comment]
I couldn't repeat the bug on the local server, but I changed the packets order a bit and optimized the number of packets sent by the server.
Some players who encountered this bug tried to repeat it, and it didn't appear.

Please let me know if the bug remains.
