### ISSUE TITLE
Packet flooding logic can be used to cheat

### ISSUE THREAD

**Issue by derpsdoesdallas** [wight-airmash/ab-server#121]
With "restore stats after disconnect", need only flood the server when you're about to die to receive a "get out of jail free" card. You get disconnected, but you keep all your ups/points. This is easily automated to produce a fairly robust cheat

**Comment by derpsdoesdallas** [comment]
I think a fair fix would be to simply discard stats on packet flood. It might suck for bad wifi people who get the packet flood thing often.

**Comment by wight-airmash** [comment]
You can just close the tab to get the same effect. The disconnection delay should prevent to use this cheat.

Connect to EU CTF in two tabs, spectate the second from the first one, then close the second and you will see that the player model will not disappear when you disconnect. Moreover, if you manage to reconnect during the delay time, you will not respawn in a safe place, but will reconnect in the place of disconnection (fly somewhere on the map and use [starmash](https://starmash.test.airmash.online/) `/reconnect` command, it disconnects and connects you as fast as possible).

**Comment by derpsdoesdallas** [comment]
Thanks for quick response, seems to be a non-issue :) Take care
