### ISSUE TITLE
90% sure heli overpowered, 20% sure Tornado underpowered

### ISSUE THREAD

**Issue by derpsderps69** [wight-airmash/ab-server#17]
Something feels wrong with balance..

- heli definitely seems overpowered. The heli bots are insanely annoying now, so much that I started zooming just to cope with it. You have very little time to respond to them. I think it is missile damage. I killed 3 bots with 2 heli volleys, which seems way too easy.

Killing Goli seems to only take 4 hits, I think it used to take at least 5?

- Tornado. I am not sure what is wrong. It may be the helis, but it may be separate. The Tornado feels much more fragile than previously. I used to be able to sit on top of a rock and collect upgrades, but now, even a single shot means having to run and hide. On the official server I could hang out on the rock for 30 minutes

**Comment by wight-airmash** [comment]
I really remember very poorly everything any airplane types except for the predator, just because I played almost only this, and most often against the same predators. Therefore, I’ll leave the issue of balance of damage for those who better remember this mechanics, or for those who can take the time to study in detail the few videos on YouTube.

I almost finished the bug fixes and the remaining features, the code will be available soon.

**Comment by wight-airmash** [comment]
Tornado Special/Goliath damage video: https://youtu.be/uUXd6zivSq8?t=90
Tornado Regular/Goliath: https://youtu.be/uUXd6zivSq8?t=150
Predator/Goliath: https://youtu.be/uUXd6zivSq8?t=97
Prowler/Goliath: https://youtu.be/uUXd6zivSq8?t=137

I understand that there are no exact values on the video, but by  the health bar we can approximately estimate the reliability of the current values.

**Comment by steamroller-airmash** [comment]
@congratulatio mentioned that they have logs from the proxy servers. Maybe that could be used to figure out the exact values and/or a formula that they follow?

**Comment by wight-airmash** [comment]
Getting the values from the original packages would be cool.

**Comment by wight-airmash** [comment]
If you feel that something is wrong with the balance of planes power, please create a new issue.

**Comment by congratulatio** [comment]
Please see [this comment](https://github.com/wight-airmash/ab-server/issues/36#issuecomment-533792701) regarding the proxy logs, they're ready for analysis now
