### ISSUE TITLE
Players sometimes stop receiving messages from the server

### ISSUE THREAD

**Issue by congratulatio** [wight-airmash/ab-server#45]
I noticed this started occurring a lot today on eu.airmash.online/ffa server, on my connections and reported from other players. This was and is happening both on 4.7.0 and 4.7.2.

Players sometimes stop receiving messages from the server, which persists until they disconnect, but the connection is not immediately closed. If the player is not whitelisted, the connection will eventually be closed by server due to a pong timeout.

This can happen at any time, but it looks like it's more likely when the player has just been killed.

If this happens when a player is whitelisted (or the whitelist is disabled), they will not be disconnected, but will not start receiving messages again. They can still fly blind - all of the commands they send are still processed by the server, and will correctly update their state. It is only the communication from the server to the client that stops.

If a player A is spectating player B, and player B stops receiving messages from the server, sometimes player A will stop receiving messages from the server at the same time. I could only reproduce this behaviour when player A and player B were both connecting from my computer. When using a different computer on a different network to connect player A, the player remained unaffected when player B stopped receiving messages from the server.

Other than the pong timeouts shortly afterwards, I can't see anything in the log that correlates with the exact time the messages stop being sent from server to client. This is with debug logging enabled.

**Comment by wight-airmash** [comment]
Are there no debug messages like "WS buffer > 0" or "WS send failed" in the logs?

As far as I understand, the requests to and from the game server are proxied by nginx. Is it possible that for some reason nginx stops (or infinitely buffers) sending answers from the game server to the client? Does config contain `proxy_buffering off;` and `tcp_nodelay on;`?

**Comment by congratulatio** [comment]
> Are there no debug messages like "WS buffer > 0" or "WS send failed" in the logs?

No I can't see anything like that in the logs.

> As far as I understand, the requests to and from the game server are proxied by nginx. Is it possible that for some reason nginx stops (or infinitely buffers) sending answers from the game server to the client?

That is a good point, I'll deploy the old airmash-proxy between ab-server and nginx to figure out which of these is responsible.

> Does config contain `proxy_buffering off;` and `tcp_nodelay on;`?

It contained the latter but not the former, I've added both now and reloaded the config - will let you know if this makes a difference.

**Comment by congratulatio** [comment]
> nginx stops (or infinitely buffers) sending answers from the game server to the client

From what I've observed, it looks like something is stopping nginx from writing to the TCP stream:

| Component | Server->client messages seen | Evidence |
| :- | :- | :- |
| ab-server | Yes | airmash-proxy observes them |
| airmash-proxy | Yes | recorded in message logs |
| nginx | Partially | debug logging indicates SSL_write is called |
| TCP stream | No | wireshark, when filtered on tcp.flags.push == 1, shows only client->server data |
| client | No | browser dev tools show only client->server data |

Thank you for your help on this, I will continue with investigating nginx behaviour.

**Comment by wight-airmash** [comment]
Thank you for checking it out. 

I also noticed that my connection didn't break when you wrote about nginx config update (I was in spectate mode at that moment and some time before). Did you use reload? I'm not sure the new config is applied.

**Comment by congratulatio** [comment]
I did use reload, perhaps that was why the new config had no effect.

In the end, I decided to start from scratch and redirect eu.airmash.online to a fresh VM running nginx and ab-server. It seems to be okay but I'll keep monitoring the logs for events suggestive of the issue, e.g. pong timeouts.
