### ISSUE TITLE
Helicopters seem too weak (health)

### ISSUE THREAD

**Issue by wight-airmash** [wight-airmash/ab-server#52]
Players who prefer helicopters often note that the balance of damage on helicopters is broken. In the original server, a helicopter with 3 and more defense upgrades and full health could also have been killed by one predator's projectile, but it was much rarer.
Needs to check the balance of the projectile damage or the damage calculation algorithm, or correct the health of the helicopter.

**Comment by jszobody** [comment]
On the flip side, I'm 90% sure a heli could _always_ be one-shot killed by a prow in the original server, even if it had full heal ups. Now an upgraded heli takes two hits to kill, even from a prow.

**Comment by wight-airmash** [comment]
> Now an upgraded heli takes two hits to kill, even from a prow.

This is the result of bad testing on my part. The main purpose was to repeat the behavior of the original, and on the original server a prowler always killed a copter with one shot.

I suppose that the calculation of damage still needs to be improved. And not unilaterally (only to reduce or only increase the damage), but perhaps it is worth revisiting the approach to calculation.

**Comment by wight-airmash** [comment]
Solved in v6.
