### ISSUE TITLE
Server does not whisper

### ISSUE THREAD

**Issue by x-airmash** [wight-airmash/ab-server#55]
Maybe I did not configure the server correct, but the us-ctf2 server does not whisper its server messages. 

For example, /upgrades should whisper the upgrade settings to me or /match the CTF match statistics, but nothing happens.

It runs on the latest master branch.

**Comment by wight-airmash** [comment]
It could be if the whitelist is turned off.

**Comment by x-airmash** [comment]
Thank you, that was the problem. I added 

> proxy_set_header X-Forwarded-For $remote_addr;

to my nginx config and now it works.
