### ISSUE TITLE
Make smoke with pred for >10 seconds = packet flooding, banhammer

### ISSUE THREAD

**Issue by derpsderps69** [wight-airmash/ab-server#56]
Some limit is too low. I got 3 clients banned with smoke, just using keyboard

SHIFT + UP + DOWN + UP + SHIFT + DOWN etc

**Comment by derpsderps69** [comment]
limits.ts suggests there is temporary kick followed by ban, but I got immediate ban in each case

**Comment by wight-airmash** [comment]
Well, instant ban is a bug for sure. 

About the current limit. If you reach it after 10 seconds it means that you reach the leaky bucket volume 100, what means that you pressed keys over 300 times during the last 10 seconds: 100 + 10 seconds * 20 (leak volume). Maybe I'm wrong, but it's not like normal behavior. I mean, it's possible, but it's very doubtful that so many meaningful movements will be made in battle. A person should have an excellent hand-eye coordination and reaction speed.
