### ISSUE TITLE
Add a command to check players status (AFK/bot)

### ISSUE THREAD

**Issue by wight-airmash** [wight-airmash/ab-server#86]
The result of the command should show the number of players playing, the number of players in spectate mode and the number of bots.

In CTF mode the statistics should be displayed for each team.

Depending on the implementation, the limit on the frequency of the command requests may be added.

From #83.

**Comment by peace2000** [comment]
Hi! This could also be achieved by adding a toggle, something like "Hide bots" or "Show human players only" to the scoreboard.
