### ISSUE TITLE
In-game menu to check all commands and instructions

### ISSUE THREAD

**Issue by peace2000** [wight-airmash/ab-server#87]
Hi! Could there be some kind of in-game menu to check all available commands and all kinds of general info, instructions concerning the game?

**Comment by wight-airmash** [comment]
There is a client command `/help`, here is a complete list of the commands supported by the server: [docs/commands.md](https://github.com/wight-airmash/ab-server/blob/master/docs/commands.md).

And this also isn't a server issue.

**Comment by peace2000** [comment]
Ok sorry, bit confused about these.
