### ISSUE TITLE
Server hosting requirements

### ISSUE THREAD

**Issue by johncalvinyoung** [wight-airmash/ab-server#89]
Any word on general hosting resources/requirements? Would love to get a version of this server deployed in US for better USA ping. What sort of hardware is needed to capably run a server?

**Comment by wight-airmash** [comment]
Of special requirements: the game is very demanding on the quality of the connection between the server and the player. In most cases these are problems on the part of the player, but the reasons may be on the server as well.

The average RAM consumption may be checked with current servers using the `/server` command, usually it's around 100±20 MB. Battle royale mode requires a little more as it has a large in-memory pre-cached spawn zone pool. 

It is important for the server to have a guaranteed CPU time to generate a stable game-tick rate (60 ticks per second).

Hardware like DigitalOcean $5 droplet should be quite enough for several instances at average load.
