### ISSUE TITLE
Special ability disabled when chat typing is open?

### ISSUE THREAD

**Issue by peace2000** [wight-airmash/ab-server#90]
Hi! Can you enable the use of special ability when the chat typing window is open?

I don't see any point why special abilities should be disabled when your typing window is open. If someone attacks me when typing, I will have to send it as unfinished or remove it completely (takes time), before I can use my special abilities again.

**Comment by wight-airmash** [comment]
This refers to the user interface, probably to this client [airmash-refugees/airmash-frontend](https://github.com/airmash-refugees/airmash-frontend). Changes in server code cannot affect this.
