### ISSUE TITLE
Mass teleporting

### ISSUE THREAD

**Issue by wight-airmash** [wight-airmash/ab-server#93]
On FFA#2 server in the interval of 4:58-5:01 PM UTC today there was a mass teleportation without significant visual delays (visually everything froze for less than a second). I was teleported from Europe to almost the North Pole (predator plane type, no speed upgrades). 

I also logged on to the server yesterday and noticed that the players were heavily distributed all over the map (as it was today after the teleport), but I didn't give it any importance. Perhaps I joined just after the same teleportation and it repeats periodically.

This kind of teleportation is possible, for example, because of the large one-time frame skip. But it has to be accompanied by a long visual delay. In less than a second, it couldn't travel that far. ~~There's probably a bug in the calculations somewhere, but it needs to debug.~~ This is a bug in players update system.

In addition, we can try to find the reason for the frame skipping. I haven't noticed it on CTF server where I play more. Among the first ideas: saving the user-stats file (JSON.stringify), the FFA server has 3x larger DB.

**Comment by congratulatio** [comment]
Thanks for the heads up on the freezing. Not sure that it's the ab-server itself at fault, there's a backup process on that server that runs regularly, which could be the culprit. I will investigate further on the cause and let you know.
