### ISSUE TITLE
Usurp-command contradiction?

### ISSUE THREAD

**Issue by peace2000** [wight-airmash/ab-server#94]
https://github.com/wight-airmash/ab-server/blob/master/docs/commands.md#usurp

> Take over the leader position in CTF. You must have higher score than the current leader. Works only with Q-bots.

https://github.com/wight-airmash/ab-server/blob/master/CHANGES.md#500-february-9-2020

> CTF: /usurp command. It allows to take over the leader position if the current leader has lower score than the player running the command. One command run per minute per team. See commands.md.

So which one is the intended info? Usurp can only be used against bots or bots and human players both?

**Comment by wight-airmash** [comment]
> Works only with Q-bots.

It is assumed that if the server uses non-Q-bots (e.g. [bots by spatie](https://github.com/spatiebot/ab-bot)), this command is useless. It doesn't matter who the leader is: a human or a bot.

The docs are written not only for players, but also for server administrators.

**Comment by peace2000** [comment]
To be honest I don't know the difference between a Q-bot and non-Q-bot.

But ok, so human players can be usurped the leader position also. This can be closed.
